language: csharp
mono: none
dotnet: 2.2
sudo: required
dist: xenial
solution: Simpper.sln
script:
  - dotnet build Simpper.sln
  - dotnet test Simpper.sln
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1