# csharp not supported, try c
language: c
os: windows
solution: Simpper.sln
script:
  - choco install sqllocaldb -y
  - choco install nuget.commandline -y
  - nuget restore
  - dotnet build
  - dotnet test
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
env:
  - EnableNuGetPackageRestore=true